### PR TITLE
Adding pdfs for capnet and in-toto

### PR DESCRIPTION
**Pull request by jhdalek55**

### CODE REVIEW

**Comment by jhdalek55** [comment]
Added pub links and the publications themselves. If OK, please push and merge.

**Comment by jhdalek55** [comment]
In the file name, I used a hyphen rather than an underscore. I'll fix the name on the graphic and then amend the copy.

**Comment by jhdalek55** [comment]
OK. This should resolve it,

**Comment by JustinCappos** [comment]
This is what I see the name as still: "papers/torres_usenix_ sec_2019.pdf
<https://github.com/secure-systems-lab/ssl-site/pull/86/files#diff-da43850b0723cd54e8e877ce06ab1c63>
"

**Pull request closed without merging**
