### PR TITLE
Update jekyll >= 3.6.3

### PR DESCRIPTION
**Pull request by lukpueh**
Fixes vulnerability of moderate severity in  (flagged by GitHub)

See commit messages for more details.

### CODE REVIEW

**Comment by lukpueh** [comment]
@dgopstein, could you take a look at my PR?

**Comment by jhdalek55** [comment]
I'm really happy you have identified and fixed flaws in the web site. Is the vulnerability anything I should be aware of? And does the patch change anything in terms of working with the site?

Thanks.

Lois

**Comment by lukpueh** [comment]
No, this was just under-the-hood stuff and is not related to the content. It does not change anything on the authoring side of the website.

**Comment by jhdalek55** [comment]
Well, thanks for that.

Lois

**Pull request merged**
