### PR TITLE
Create 2023-10-20-uptane-siterevision.md

### PR DESCRIPTION
**Pull request by jhdalek55**
Adding new blog post about the revised Uptane webpage

### CODE REVIEW

**Comment by jhdalek55** [comment]
@adityasaky All the checks passed on this but I got an error message when trying to commit. When you get a chance can you check on this and then merge it. The text was reviewed offline by Justin and several other Uptane members. Thanks.

**Comment by jhdalek55** [comment]
@adityasaky when I just checked the website, I see a bullet point added on the blog page but nothing else. Why is the title and link not appearing?

**Comment by adityasaky** [comment]
I just fixed that. https://ssl.engineering.nyu.edu/blog/2023-10-20-uptane-siterevision

**Comment by jhdalek55** [comment]
Many thanks.

Lois

**Pull request merged**
