### PR TITLE
Adding to Scudo blog

### PR DESCRIPTION
**Pull request by jhdalek55**
When I initially post this, I accidentally committed it to master. Hope that didn't screw things up. I have to make some edits and add a graphic so I will do the balance of this as a Pull Request

### CODE REVIEW

**Comment by adityasaky** [comment]
It should be okay for this repo.

**Comment by jhdalek55** [comment]
@adityasaky I think this is good to go. Everyone reviewed the content in the Google doc. Maybe doublecheck the links. Otherwise, please approve, merge and push. I dated it for tomorrow in case you didn't have time ti look at it today

**Comment by adityasaky** [comment]
Can we update https://www.solarwinds.com/fr/resources/whitepaper/setting-the-new-standard-in-secure-software-development-the-solarwinds-next-generation-build-system/delivery to https://www.solarwinds.com/resources/whitepaper/setting-the-new-standard-in-secure-software-development-the-solarwinds-next-generation-build-system/delivery? The first is their french website.

**Comment by jhdalek55** [comment]
Sure. I'll fix that now.

**Review by adityasaky — APPROVED** [review]

**Comment by adityasaky** [comment]
I'll push it out tomorrow.

**Comment by jhdalek55** [comment]
Thanks.

**Pull request merged**
