### PR TITLE
Replace Travis with Github Action

### PR DESCRIPTION
**Pull request by adityasaky**
Looks like we're having some trouble with Travis now based on the free plan / credits.

This is what I see:

image

### CODE REVIEW

**Comment by adityasaky** [comment]
This passed on my fork: https://github.com/adityasaky/ssl-site/pull/1

**Comment by jhdalek55** [comment]
Thanks for looking into this. Let me know if this will change how we do updates. Thanks.

**Comment by jhdalek55** [comment]
Aditya, what is the hold-up here? Do we need an approval from Justin or someone else? Or is this a mechanical fix for which we need NYU?

**Comment by adityasaky** [comment]
Yep, if I'm not mistaken, we need someone with admin rights on this repository.

**Pull request merged**
