### PR TITLE
Adding papers and press

### PR DESCRIPTION
**Pull request by jhdalek55**
Added the most recent atoms paper to the publications page

### CODE REVIEW

**Comment by jhdalek55** [comment]
Don't fix this tonight...its not urgent...but this still looking to do a Travis build and its still giving the "Travis CI waiting for status to be reported.

I'm going to stop till you have a chance to review this tomorrow.

**Comment by adityasaky** [comment]
Fixed.

**Comment by jhdalek55** [comment]
I'm putting a few other updates here, so hold off on merging this one.

**Comment by jhdalek55** [comment]
Ok. I have something I have to do now. I guess I'll take a look tomorrow. All I did was add a paper title to the publications section. Off the top of my head I don't see what I did wrong.

I hate yaml.

**Comment by adityasaky** [comment]
Fixed! The second ampersand was the issue.

**Comment by jhdalek55** [comment]
Thanks. I thought about that ampersand. I will keep that in mind.

**Comment by jhdalek55** [comment]
@adityasaky you can merge this PR now. It was just routine updates.
I will be adding a blog post, but probably not till after I get back from vacation, so these corrections don't have to wait for that. Thanks.

**Pull request merged**
