### PR TITLE
Adding Uptane blog

### PR DESCRIPTION
**Pull request by jhdalek55**
@JustinCappos, you might want to take a look at this one. I revised it yesterday...mostly by rearranging the order of paragraphs. This was originally crafted as a press release, so it just felt a bit awkward in places (as most people reading this will know enough about Uptane to not need some of the background information in the release). So please take a look if you'd like

### CODE REVIEW

**Comment by jhdalek55** [comment]
FYI--the Travis Build is taking way too long to build. Last night it was a two-hour wait for the other blog post. Friday night,  I had a  40 minute wait for a check when all I was loading was a photo.

**Comment by lukpueh** [comment]
> FYI--the Travis Build is taking way too long to build. Last night it was a two-hour wait for the other blog post. Friday night, I had a 40 minute wait for a check when all I was loading was a photo.

The long builds where caused by the brown out of travis-ci.org. I just migrated this repo to the new travis-ci.com and builds take less than half a minute now.

**Comment by lukpueh** [comment]
@jhdalek55, if you got some notifications about commits being pushed to this PR (and to #119) please ignore. I just tested if the migration worked. The test commits I pushed are removed again.

**Comment by jhdalek55** [comment]
Thanks, Lukas, for making this adjustment.

**Comment by jhdalek55** [comment]
Given there have been no further comments let's deploy this one too.

**Pull request merged**
