### PR TITLE
FIX: ignore vendor directory

### PR DESCRIPTION
**Pull request by SantiagoTorres**
There's a broken template in the vendor directory, which makes things blow up. Ignore the vendor directory...

Also, it appears I was removed access to this repository, so I can't push directly (if I ever was able that is)

### CODE REVIEW

**Comment by jhdalek55** [comment]
So...I have to reach out to Dan on this?


Lois

On Tue, Jan 22, 2019 at 12:51 PM, Santiago Torres wrote:

There's a broken template in the vendor directory, which makes things 
blow up. Ignore the vendor directory...

Also, it appears I was removed access to this repository, so I can't 
push directly (if I ever was able that is)



You can view, comment on, or merge this pull request online at:

  https://github.com/secure-systems-lab/ssl-site/pull/61 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_secure-2Dsystems-2Dlab_ssl-2Dsite_pull_61&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=oayTAoYss-ERZAvo8Hr2kCmiXYAL8BQFiDlOxL8spco&s=6YvGurbr7TChJSZGaNWRuYZMLCDckweOUSUmID5umh0&e=>

Commit Summary

    * FIX: ignore vendor directory


File Changes

    *
     M
     _config.yml 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_secure-2Dsystems-2Dlab_ssl-2Dsite_pull_61_files-23diff-2D0&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=oayTAoYss-ERZAvo8Hr2kCmiXYAL8BQFiDlOxL8spco&s=DN0SHLIJk-y5wRceG8QGYAUHsxIBfpXepqGEUjY7IP0&e=>
     (2)



Patch Links:

    * https://github.com/secure-systems-lab/ssl-site/pull/61.patch 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_secure-2Dsystems-2Dlab_ssl-2Dsite_pull_61.patch&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=oayTAoYss-ERZAvo8Hr2kCmiXYAL8BQFiDlOxL8spco&s=GjIY_72ahmGyzzrNnNmXCfa9St4a6O18kL44MH-mcaQ&e=>
    * https://github.com/secure-systems-lab/ssl-site/pull/61.diff 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_secure-2Dsystems-2Dlab_ssl-2Dsite_pull_61.diff&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=oayTAoYss-ERZAvo8Hr2kCmiXYAL8BQFiDlOxL8spco&s=czk8qOqf9R1CZLiW2Zzy6rNAy1-zUoTBW_5Z_AHDFno&e=>



—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_secure-2Dsystems-2Dlab_ssl-2Dsite_pull_61&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=oayTAoYss-ERZAvo8Hr2kCmiXYAL8BQFiDlOxL8spco&s=6YvGurbr7TChJSZGaNWRuYZMLCDckweOUSUmID5umh0&e=> 
, or mute the thread 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AN5qX218F-5FarDc69VcEOCXe5iGSuLuHfks5vF0-2DPgaJpZM4aNMjE&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=oayTAoYss-ERZAvo8Hr2kCmiXYAL8BQFiDlOxL8spco&s=8jLBuDVcfsEzXnEfrVjXDHbwDD011bgGm5FzoG8SWtc&e=> 
.

**Comment by dgopstein** [comment]
My checkout doesn't have a `version` dir. Do you know where yours comes from?

**Comment by SantiagoTorres** [comment]
Maybe, it's an issue with the way it's deployed on github, and I don't know what they do in the backend to build (I'm not sure if they vendor everything). To contextualize, this is the error:

```
[santiago@LykOS ssl-site]$ bundle exec jekyll serve                                                                                                                                                              
Configuration file: /home/santiago/workbench/ssl-site/_config.yml                                                                                                                                                
            Source: /home/santiago/workbench/ssl-site                                                                                                                                                            
       Destination: /home/santiago/workbench/ssl-site/_site                                                                                                                                                      
 Incremental build: disabled. Enable with --incremental                                                                                                                                                          
      Generating...                                                                                                                                                                                              
             Error: could not read file /home/santiago/workbench/ssl-site/vendor/bundle/ruby/2.6.0/gems/jekyll-3.8.4/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb: Invalid date '<%= Time.n
ow.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.6.0/gems/jekyll-3.8.4/lib/site_template/_posts/00[santiago@LykOS ssl-site]$ bundle exec jekyll serve                                                                                                                                                              
Configuration file: /home/santiago/workbench/ssl-site/_config.yml                                                                                                                                                
            Source: /home/santiago/workbench/ssl-site                                                                                                                                                            
       Destination: /home/santiago/workbench/ssl-site/_site                                                                                                                                                      
 Incremental build: disabled. Enable with --incremental                                                                                                                                                          
      Generating...                                                                                                                                                                                              
             Error: could not read file /home/santiago/workbench/ssl-site/vendor/bundle/ruby/2.6.0/gems/jekyll-3.8.4/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb: Invalid date '<%= Time.n
ow.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.6.0/gems/jekyll-3.8.4/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front ma
tter.                                                                                                                                                                                                            
             ERROR: YOUR SITE COULD NOT BE BUILT:                                                                                                                                                                
                    ------------------------------------                                                                                                                                                         
                    Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.6.0/gems/jekyll-3.8.4/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' do$s not have a valid date in the YAML front matter.
00-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front ma
tter.                                                                                                                                                                                                            
             ERROR: YOUR SITE COULD NOT BE BUILT:                                                                                                                                                                
                    ------------------------------------                                                                                                                                                         
                    Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.6.0/gems/jekyll-3.8.4/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' do$s not have a valid date in the YAML front matter.
```

**Comment by SantiagoTorres** [comment]
> My checkout doesn't have a version dir. Do you know where yours comes from?

`vendor` is a dir that's created when you install the gems locally (not as user, not as system). I don't see it in the instructions, but that's apparently the recommended way to install things.

**Comment by SantiagoTorres** [comment]
Either way, the error appears to be with the template getting pulled in and being compiled, to which I don't know if that's the error with deployment (everything else seems to be ok)

**Comment by dgopstein** [comment]
This problem did not appear to affect production, so we'll leave this commit out for now. If you find a good solution to this problem on the development side, please post it here.

**Pull request closed without merging**
